services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.prod

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
