# Generated by Django 5.2 on 2025-04-11 01:50

from django.db import migrations
from django.core.management import call_command


def load_fixtures(apps, schema_editor):
    call_command("loaddata", "kanban/fixtures/statuses.json")
    call_command("loaddata", "kanban/fixtures/task_templates.json")


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixtures),
    ]
