name: Backend tests
on:
  push:
    branches:
      - dev
jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build backend container
        run: docker compose -f docker-compose.dev.yaml build backend

      - name: Run migrations
        run: docker compose -f docker-compose.dev.yaml run --rm backend migrate

      - name: Run tests
        run: docker compose -f docker-compose.dev.yaml run --rm backend test