name: Deploy to Production

on:
  push:
    branches:
      - master  # o la rama que uses para producción

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci
      working-directory: ./frontend

    - name: Build frontend
      run: |
        VITE_BACKEND_URL=${{ secrets.BACKEND_FRONTEND_URL }} npm run build
      working-directory: ./frontend

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    - name: Sync frontend to S3
      run: aws s3 sync ./frontend/dist/ s3://kanban-app-frontend --delete

    - name: Invalidate CloudFront cache
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.FRONTEND_CLOUDFRONT_ID }} --paths "/*"

  # Opcional: deploy backend si querés
  deploy-backend:
    needs: deploy-frontend
    runs-on: ubuntu-latest

    steps:
    - name: SSH and pull backend repo
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd kanban-app
          git pull origin master
          docker compose -f docker-compose.prod.yaml up -d --build